### ISSUE TITLE
Bullet graph

### ISSUE THREAD

**Issue by robertogilsaura** [jbkunst/highcharter#482]
Hi @jbkunst .
I'm trying to chart a bullet graph, but it doesn't run properly. Unfortunately, in plot window, canvas is white, and there isn't image.
My code is ...

```
library(highcharter)
highchart() %>%
    hc_chart(inverted = TRUE, type="bullet") %>%
    hc_add_dependency("modules/bullet.js") %>% 
    hc_title(text="TITULO 1") %>%
    hc_xAxis(categories="X CATEGORIA") %>%
    hc_plotOptions(series = list(pointPadding = 0.25, borderWidth = 0, color = "blue", targetOptions=list(width = '100%'))) %>%
    hc_yAxis(plotBands = list(list(from = 0, to = 50,color = "red"), list(from = 50, to = 80,color = "yellow"), list(from = 80, to = 100,color = "green")), title = "TITULO 2") %>%
    hc_add_series(data=list(y=50, target=90))
```

I have read in one of your examples 

`hc_add_dependency("modules/bullet.js")`

 but I don't know if I use in a correct way. Is it possible in RStudio or in RServer run this chart?

_Note I use RStudio for preparing scripts but Rserver for deploying in dashboards_

A lot of thanks for your contribution, Joshua.

**Comment by jbkunst** [comment]
Hi @robertogilsaura !

Sorry for the late response. First of all, you don't need add the dependency, now is added by default.

You need another `list` in the `hc_add_series` to fix your example: `...  hc_add_series(data=list(list(y=50, target=90)))`.

And you can check other example in https://github.com/jbkunst/highcharter/blob/master/dev/charts_and_type_series/bullet.R.

Regards!

**Comment by robertogilsaura** [comment]
Hi @jbkunst , thanks for your response. I found other solution for this graph but **I'm very interested with highcharter solution** I prefer this solution to ggplot2

I run the code example (https://github.com/jbkunst/highcharter/blob/master/dev/charts_and_type_series/bullet.R) in my Rstudio and output in viewer is empty. My sessionInfo() ...
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] forcats_0.3.0     stringr_1.3.1     dplyr_0.7.8      
 [4] purrr_0.2.5       readr_1.3.1       tidyr_0.8.2      
 [7] tibble_2.0.1      ggplot2_3.1.0     tidyverse_1.2.1  
[10] highcharter_0.7.0

loaded via a namespace (and not attached):
 [1] zoo_1.8-4         tidyselect_0.2.5  haven_2.0.0      
 [4] lattice_0.20-38   colorspace_1.4-0  generics_0.0.2   
 [7] htmltools_0.3.6   yaml_2.2.0        rlang_0.3.1      
[10] pillar_1.3.1      withr_2.1.2       glue_1.3.0       
[13] TTR_0.23-4        modelr_0.1.2      readxl_1.2.0     
[16] bindrcpp_0.2.2    bindr_0.1.1       plyr_1.8.4       
[19] quantmod_0.4-13   munsell_0.5.0     gtable_0.2.0     
[22] cellranger_1.1.0  rvest_0.3.2       htmlwidgets_1.3  
[25] curl_3.2          broom_0.5.1       xts_0.11-2       
[28] Rcpp_1.0.0        backports_1.1.3   scales_1.0.0     
[31] jsonlite_1.6      hms_0.4.2         digest_0.6.18    
[34] stringi_1.2.4     rlist_0.4.6.1     grid_3.4.4       
[37] cli_1.0.1         tools_3.4.4       magrittr_1.5     
[40] lazyeval_0.2.1    crayon_1.3.4      whisker_0.3-2    
[43] pkgconfig_2.0.2   xml2_1.2.0        data.table_1.12.0
[46] lubridate_1.7.4   assertthat_0.2.0  httr_1.4.0       
[49] rstudioapi_0.9.0  R6_2.3.0          igraph_1.2.2     
[52] nlme_3.1-137      compiler_3.4.4  
```
Other highcharts runs properly ... Can there be a problem with package compatibility?

Thanks in advance ...

Rober

**Comment by mariana-yn** [comment]
If you still want to run this example, I managed to reproduce it after editing the file `highchart.yaml` inside the htmlwidgets folder of the highcharter package. Just remove the **#** before `- modules/bullet.js` and I believe the chart will appear.

```
 dependencies:
  - name: jquery
    version: 1.11.1
    src: "htmlwidgets/lib/jquery"
    script: jquery.min.js
  - name: proj4js
    version: 2.3.15
    src: "htmlwidgets/lib/proj4js"
    script: proj4.js
  - name: highcharts
    version: 6.0.3
    src: "htmlwidgets/lib/highcharts-6.0.3"
    script:
    - highcharts.js
    - highcharts-3d.js
    - highcharts-more.js
    - modules/stock.js
    - modules/heatmap.js
    - modules/treemap.js
    - modules/annotations.js
    - modules/boost.js
    - modules/data.js
    - modules/drag-panes.js
    - modules/drilldown.js
    - modules/funnel.js
    - modules/item-series.js
    - modules/offline-exporting.js
    - modules/overlapping-datalabels.js
    - modules/parallel-coordinates.js
    - modules/sankey.js
    - modules/solid-gauge.js
    - modules/streamgraph.js
    - modules/sunburst.js
    - modules/vector.js
    - modules/wordcloud.js
    - modules/xrange.js 
    - modules/exporting.js
    - modules/export-data.js    
#    - modules/static-scale.js
#    - modules/grid-axis.js
#    - modules/broken-axis.js
#    - modules/series-label.js
#    - modules/pareto.js    
    - modules/bullet.js    
```
